from django import forms
from django.forms.fields import ChoiceField,MultipleChoiceField
from django.forms.widgets import RadioSelect ,CheckboxSelectMultiple

class ContactForm(forms.Form):  
    first_name = forms.CharField(max_length=100,label="First Name",required=True)
    last_name = forms.CharField(max_length=100,label="Last Name",required=True)
    group = forms.CharField(max_length=100,label="Group",required=False)
    email = forms.EmailField (max_length =200,label="Email",required=False)
    python_level_choices = (('1','Beginner'),('2','Intermediate'),('3','Advanced'))
    python_level = ChoiceField(widget=RadioSelect, choices=python_level_choices,label="Python Level",required=True)
    interests = forms.CharField(widget=forms.Textarea(attrs={'rows':5, 'cols':45}),label="Interests",required=True)
    work_field=forms.CharField(widget=forms.Textarea(attrs={'rows':5, 'cols':45}),label="Work Field",required=False)
    libraries_choices =(('1','numpy'),('2','pandas'),('3','matplotlib'),('4','scikit-learn'))
    libraries_used= MultipleChoiceField(widget=CheckboxSelectMultiple, choices=libraries_choices,label="Python Libraries Used :",required=False)
    data_structure_choices =(('1','arrays'),('2','listes'),('3','tuples'),('4','dataframes'),('5','series'))
    data_structures= MultipleChoiceField(widget=CheckboxSelectMultiple, choices=data_structure_choices,label="Which data structures do you know ?",required=False)
    python_characters_choices =(('1','char'),('2','chr'),('3','character'),('4','It does not exist'))
    data_type_char=ChoiceField(widget=RadioSelect, choices=python_characters_choices,label=" What is the data type for a character in Python ?",required=False)
    for_loop_syntax=forms.CharField(max_length=600,label="What is the syntax of a for loop to iterate over the elements of a list L ?",required=False)
    range_args=forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'cols':45}),label=" What are the arguments of a range function ?",required=False)
    tools=(('1','numpy'),('2','boucle'))
    matrix_tool=ChoiceField(widget=RadioSelect, choices=tools,label="What is the fastest tool to make calculations on a matrix ?",required=False)
    hobbies=forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'cols':45}),label="What are your hobbies ?",required=True)
    job=forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'cols':45}),label="What is job do you consider doing in the future ?",required=False)
    level_of_detail = forms.CharField(max_length=200,label="Do you prefer detailed or summarized instructions ?",required=False)
    valeur_dictionnaire_choices=(('1','index'),('2','outil'))
    dico_test=ChoiceField(widget=RadioSelect, choices=valeur_dictionnaire_choices,label="What do we use to access a value in a dictionary ?",required=False)
    condition=forms.CharField(max_length=200,label="What keywords do we use to check a condition ?",required=False)
    lenght=forms.CharField(max_length=200,label="Which function allows determining the size of a dataframe ?",required=False)
    arg_attributes=forms.CharField(max_length=200,label="What argument allows accessing the attributes of an object in a class method ?",required=False)
    na_values_instruction=forms.CharField(max_length=200,label="What instruction allows to have the total number of NA values ​​for each variable of a dataframe ?",required=False)
    ml_method=forms.CharField(max_length=200,label="Which method allows to identify the best parameters of a ML model ?",required=False)